### ISSUE TITLE
Inconsistency between spec validation & workflow execution

### ISSUE THREAD

**Issue by planetf1** [i-am-bee/beeai-labs#178]
Testing in bee-hive-demos
```console
(bee-hive-demos-py3.12) ➜  bee-hive-demos git:(dev/jonesn/activitymerge) /Users/jonesn/AI/bee/bee-hive-demos/.venv/bin/python /Users/jonesn/AI/bee/bee-hive-demos/demos/activity-planner.ai/src/run.py
Enable the weather tool in the Bee UI
Enable the weather tool in the Bee UI
Enable the web_search tool in the Bee UI
Enable the web_search tool in the Bee UI
Traceback (most recent call last):
  File "/Users/jonesn/AI/bee/bee-hive-demos/demos/activity-planner.ai/src/run.py", line 32, in <module>
    test_agent_runs()
  File "/Users/jonesn/AI/bee/bee-hive-demos/demos/activity-planner.ai/src/run.py", line 28, in test_agent_runs
    result = workflow.run()
             ^^^^^^^^^^^^^^
  File "/Users/jonesn/AI/bee/bee-hive-demos/.venv/lib/python3.12/site-packages/bee_hive/workflow.py", line 61, in run
    return self._condition()
           ^^^^^^^^^^^^^^^^^
  File "/Users/jonesn/AI/bee/bee-hive-demos/.venv/lib/python3.12/site-packages/bee_hive/workflow.py", line 83, in _condition
    prompt = self.workflow["spec"]["prompt"]
             ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'prompt'
```
occurs given a workflow:
```yaml
apiVersion: beehive/v1alpha1
kind: Workflow
metadata:
  name: beehive-deployment
  labels:
    app: mas-example
spec:
  strategy:
    type: condition
    output: nonal
  template:
    metadata:
      labels:
        app: mas-example
    agents:
      - name: current-affairs
      - name: hot-or-not
      - name: cold-activities
      - name: hot-activities
    prompt: New York City
    steps:
      - name: current-affairs
        agent: current-affairs
        condition:
        - default:
          do: hot-or-not
      - name: hot-or-not
        agent: hot-or-not
        condition:
        - if: (input.find('hotter') != -1)
          do: cold-activities
          else: hot-activities
      - name: end
```
which passes schema validation ok

**Comment by planetf1** [comment]
Note that though we are using a simple runner in demos, we are using the latest Workflow class from bee-hive (pulled in as a dependency)

**Comment by planetf1** [comment]
Conversely, the workflow for a crewai demo (before the validator works) fails validation:
```
(bee-hive-demos-py3.12) ➜  activity-planner-demo git:(dev/jonesn/activitymerge) beeAI validate ../../../bee-hive/tools/workflow_schema.json workflow.yaml 
validating workflow.yaml with schema ../../../bee-hive/tools/workflow_schema.json
Error: "'location'"
```

```yaml
apiVersion: beehive/v1alpha1
kind: Workflow
metadata:
  name: beehive-deployment
  labels:
    app: activity-planner-demo
spec:
  strategy:
    type: sequence
    output: nonal
  template:
    metadata:
      labels:
        app: activity-planner-demo
    agents:
      - name: activity_planner.ActivityPlannerCrew.activity_crew
  prompt: {"location": "San Francisco"}
  steps:
    - name: begin
      agent: activity_planner.ActivityPlannerCrew.activity_crew

```
Yet it runs ok:
```
(bee-hive-demos-py3.12) ➜  bee-hive-demos git:(dev/jonesn/activitymerge) ✗ demos/activity-planner-demo/run.py 
Running CrewAI agent: activity_planner.ActivityPlannerCrew.activity_crew with prompt: {'location': 'San Francisco'}
# Agent: Activity Planner
## Task: Find a list of 5 activities to do in the cold or wet weather in San Francisco. Make sure the information is current as of 2025.

^C
```

The confusion may have arisen from the embedded tabs in the original schema which resulted in what appeared to be a change of some elements (steps, prompt etc) out of 'template' and up a level. This was purely visual, and corrected in https://github.com/i-am-bee/bee-hive/pull/154

**Comment by planetf1** [comment]
Testing this again after the repo merge (and with wip PR #189) - this time against all of our workflow files:
```
(bee-hive-py3.12) ➜  bee-hive git:(migratedemofix) ~/bin/validate-all.sh   
====
./test/yamls/workflows/funnier_workflow.yaml
====
validating ./test/yamls/workflows/funnier_workflow.yaml with schema tools/workflow_schema.json
Error: "'name'"

====
./test/yamls/workflows/conditional_workflow.yaml
====
validating ./test/yamls/workflows/conditional_workflow.yaml with schema tools/workflow_schema.json
YAML file is valid.

====
./test/yamls/workflows/simple_workflow.yaml
====
validating ./test/yamls/workflows/simple_workflow.yaml with schema tools/workflow_schema.json
YAML file is valid.

====
./test/examples/condition_workflow.yaml
====
validating ./test/examples/condition_workflow.yaml with schema tools/workflow_schema.json
Error: YAML file is NOT valid:
 'agent' is a required property
Error: executing command: 1

====
./bee-hive/tests/crewai/workflow.yaml
====
validating ./bee-hive/tests/crewai/workflow.yaml with schema tools/workflow_schema.json
Error: "'name'"

====
./bee-hive/tests/bee/workflow.yaml
====
validating ./bee-hive/tests/bee/workflow.yaml with schema tools/workflow_schema.json
Error: "'name'"

====
./bee-hive/tests/workflow/workflow.yaml
====
validating ./bee-hive/tests/workflow/workflow.yaml with schema tools/workflow_schema.json
Error: "'name'"

====
./bee-hive-demos/demos/weather-checker.ai/workflow.yaml
====
validating ./bee-hive-demos/demos/weather-checker.ai/workflow.yaml with schema tools/workflow_schema.json
Error: "'name'"

====
./bee-hive-demos/demos/summary.ai/workflow.yaml
====
validating ./bee-hive-demos/demos/summary.ai/workflow.yaml with schema tools/workflow_schema.json
YAML file is valid.

====
./bee-hive-demos/demos/activity-planner.ai/workflow.yaml
====
validating ./bee-hive-demos/demos/activity-planner.ai/workflow.yaml with schema tools/workflow_schema.json
Error: YAML file is NOT valid:
 'agent' is a required property
Error: executing command: 1

====
./bee-hive-demos/demos/activity-planner-crewai.ai/workflow.yaml
====
validating ./bee-hive-demos/demos/activity-planner-crewai.ai/workflow.yaml with schema tools/workflow_schema.json
Error: "'location'"

```
This INCLUDES 3 specific testcases

**Comment by planetf1** [comment]
For example the crewai demo fails:
```
====
./bee-hive-demos/demos/activity-planner-crewai.ai/workflow.yaml
====
validating ./bee-hive-demos/demos/activity-planner-crewai.ai/workflow.yaml with schema tools/workflow_schema.json
Error: "'location'"
```

Yet this code runs :

```
(bee-hive-py3.12) ➜  bee-hive git:(migratedemofix) /Users/jonesn/AI/bee/bee-hive/.venv/bin/python /Users/jonesn/AI/bee/bee-hive/bee-hive-demos/demos/activity-planner-crewai.ai/run.py
Running CrewAI agent: activity_planner.ActivityPlannerCrew.activity_crew with prompt: {'location': 'San Francisco'}
# Agent: Activity Planner
## Task: Find a list of 5 activities to do in the cold or wet weather in San Francisco. Make sure the information is current as of 2025.
```

**Comment by psschwei** [comment]
Will try to reproduce. How did you run the crew demo workflow that failed?

**Comment by planetf1** [comment]
@psschwei `./bee-hive-demos/demos/activity-planner-crewai.ai/run.py` from root

That directory has the workflow.yaml

Validation was attempted with
```
(bee-hive-py3.12) ➜  bee-hive git:(imports) ✗ beeAI validate tools/workflow_schema.json ./bee-hive-demos/demos/activity-planner-crewai.ai/workflow.yaml 
validating ./bee-hive-demos/demos/activity-planner-crewai.ai/workflow.yaml with schema tools/workflow_schema.json
Error: "'location'"
```

Not looked in detail today.

**Comment by psschwei** [comment]
Found the problem

The CrewAI workflow has:

https://github.com/i-am-bee/bee-hive/blob/8c9c2ba2c48d42ca3649fafe771095f7d303c08a/bee-hive-demos/demos/activity-planner-crewai.ai/workflow.yaml#L17

but the workflow schema specifies the prompt be a string:

https://github.com/i-am-bee/bee-hive/blob/8c9c2ba2c48d42ca3649fafe771095f7d303c08a/tools/workflow_schema.json#L69-L71

Can the CrewAI prompt be passed as a string? say

 ```yaml
spec: 
    prompt: '{"location": "San Francisco"}'
```

If not, then we may need to revisit the type for prompt...

**Comment by planetf1** [comment]
Ah! Thanks for checking - I didn't associate the two (I was very aware of the issue) and ran out of time to debug. But addressing the input/output for that agent is the next task anyway.

There's still potentially some followup
 - the other validation failures
 - that we should validate prior to execution IMO - we couldn't do this until we got things matched up, but once we've addressed the above we should. future iteration though.

**Comment by planetf1** [comment]
I've found a general pattern that is causing some schema validations.

In the schema we have a list of agents. The schema says:
```json
            "agents": {
              "type": "array",
                "items": {
                "type": "string"
              }
            },
```
This means a simple list ie
```yaml
agents:
  - agent1
  - agent 2
```

Yet many have
```yaml
agents:
  - name: agent1
  - name: agent2
```

Opening PR to address this change so we can review/evaluate.

There are other schema mismatches including
- the crew issue above -- later
- The use of an 'end' step (schema requires all steps to have an agent specified)
