### ISSUE TITLE
use case: parallelism

### ISSUE THREAD

**Issue by psschwei** [i-am-bee/beeai-labs#23]
Part of https://github.com/i-am-bee/bee-hive/issues/6

As a user, I want to have an example of building a workflow with parallel executions and run it via the bee-hive

**Comment by planetf1** [comment]
We will also need some bracketing concept as we need to control when the parallel execution threads join back together again. ie
1 - 2|3|(4-5) - 6
1 runs alone.
Then we start 2,3,4 in parallel. But 5 must run after 4 (it’s a series group), and we don’t run 6 until 2,3,4,5 are all complete - one can expand to all kinds of flows.

**Comment by psschwei** [comment]
I think something like a `dependsOn` option could work here, for a 1 - (23) - 4 workflow something like:

```yaml
workflow:
  - step:
     name: step1
  - step:
     name: step2
     dependsOn: step1
  - step:
     name: step3
     dependsOn: step1
  - step:
     name: step4
     dependsOn: 
      - step2
      - step3
      
```

Essentially we need to build a DAG by creating edges between nodes (agents)
