### ISSUE TITLE
Add ability to loop in workflow

### ISSUE THREAD

**Issue by maximilien** [i-am-bee/beeai-labs#236]
This came from discussion in: https://github.com/i-am-bee/beeai-labs/pull/234#issuecomment-2666884610

What about having a loop feature instead so something like:

```yaml
...
    steps:
      - name: step1
        agent: test1
      while: (len(input.list) == 0)
        do: step2
      - name: step2
        agent: test2
...

```

Of course we could also do it like this:

```yaml
...
    steps:
      - name: step1
         agent: test1
      loop: step2
        until: (len(input.list) == 0)
      - name: step2
         agent: test2
...
```

- [x] schema changes for `loop`
- [x] agree on approach with @akihikokuroda 
- [x] implement new loop structure in `workflow.py`
- [ ] add a specific test running `loop_workflow.yaml`

**Comment by maximilien** [comment]
OK some changes to proposal but should work well. Proposing:

```yaml
...
    steps:
      - name: step1
        agent: test1
        loop: 
            step: step2
            until: (input.happy == True)
      - name: step2
        agent: test2        
...
```

Which leads to schema addition:

```json
                  "loop": {
                    "type": "object",
                    "description": "looping construct",
                    "items": {
                      "type": "object",
                      "properties": {
                        "step": {
                          "type": "string"
                        },
                        "until": {
                          "type": "string"
                        }
                      }
                    }
                  }
```

Let me push a PR with schema changes and example and work on changes to `workflow.py` to support once we all agree.
