### ISSUE TITLE
Schema: define basic schema for workflow

### ISSUE THREAD

**Issue by psschwei** [i-am-bee/beeai-labs#27]
As a user, I want a defined schema to write my beehive workflow in. 

This is related with #47 and #48

**Comment by maximilien** [comment]
Did you upload the example workflow that you presented in demo @psschwei?

Also similar question @developer-gliu?

I want to ensure schema matches. ideally we should have these in a `demo` or `use-case` directory. LMK

**Comment by developer-gliu** [comment]
Yup, I have it in a branch currently. I don't exactly have a demo folder, but I just followed pauls current structure. 
The hierarchy is the examples -> pauls example folder / my example folder -> code
<img width="358" alt="Screenshot 2025-01-06 at 9 24 57 PM" src="https://github.com/user-attachments/assets/d34d5a56-6a13-4c41-a2f2-e5bb1bd7d9ac" />

**Comment by psschwei** [comment]
> Did you upload the example workflow that you presented in demo @psschwei?
Yes, it's in a top-level `examples` directory, though that may change as there's some discussion about having separate examples directories for each subproject rather than a single one for all

**Comment by maximilien** [comment]
OK folks, so for the schema I did some research and the best approach is to use JSON schema. Since YAML can be converted to JSON then the same JSON schema can be used to validate the YAML. This is my first attempt:

Proposed schema for the current agreed upon workflow (does not include conditional since we need to agree on that. See my comment in PR #124 

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/i-am-bee/bee-hive/workflow.schema.json",
  "title": "Bee Hive",
  "description": "A schema for defining Bee Hive workflows in YAML or JSON",
  "type": "object",
  "properties": {
    "apiVersion": "string",
    "kind": "string",
    "metadata": {
      "name": "string",
      "labels": "object"
    },
    "spec": {
      "strategy": {
        "type": "sequence"
      },
      "template": {
        "metadata": {
          "name": "string",
          "labels": "object"
        }
      }
    },
    "agents": [],
    "exception": "string",
    "steps": []
  }
}

```

A valid JSON and YAML for this schema follows:

```json
{
  "apiVersion": "beehive/v1",
  "kind": "Workflow",
  "metadata": {
    "name": "beehive-deployment",
    "labels": {
      "app": "example2"
    }
  },
  "spec":{
    "strategy": {
      "type": "sequence"
    },
    "template": {
      "metadata": {
        "name": "beehive-deployment",
        "labels": {
          "app": "example",
          "use-case": "test"
        }
      }
    },  
    "agents": [
        "agent1",
        "agent2",
        "agent3"
    ],
    "exception": "step4",
    "steps": [
       "step1",
       "step2",
       "step3",
       "step4"
    ],
    "step1": {
       "agent": "agent1"
    },
    "step2": {
       "agent": "agent2"
    },
    "step3": {
       "agent": "agent1"
    },
    "step4": {
       "agent": "agent3"
    }
  }
}
```

```yaml

---
apiVersion: beehive/v1
kind: Workflow
metadata:
  name: beehive-deployment
  labels:
    app: example2
spec:
  strategy:
    type: sequence
  template:
    metadata:
      name: beehive-deployment
      labels:
        app: example
        use-case: test
  agents:
  - agent1
  - agent2
  - agent3
  exception: step4
  steps:
  - step1
  - step2
  - step3
  - step4
  step1:
    agent: agent1
  step2:
    agent: agent2
  step3:
    agent: agent1
  step4:
    agent: agent3
```

Please comment directly here. I will submit my PR that uses this schema and the two tests workflows for this issue. Finally, since we will need various iterations as we evolve the workflow language and schema, I will open a similar issue for each iterations.

CC: @psschwei @akihikokuroda @planetf1

**Comment by developer-gliu** [comment]
Just to prevent possible issues, for the `exception` field in the original schema definition, would it make sense to enforce that the string actually is part of `steps` also? Otherwise, as long the input is a string, then it would be valid causing an error.

The rest of the schema make sense to me

**Comment by planetf1** [comment]
* Can we add a version to the workflow spec ie maybe it's `https://github.com/i-am-bee/bee-hive/workflow.schema-v1.0.json. Perhaps also add a `specVersion`parameter (both of these are how CycloneDX seems to do it - but there are many ways...)
* I think it's fine the schema evolves changes in a breaking way in our first few iterations - we're still learning a lot. 
* We only have steps, and have a sequence strategy. *in future* I think we need the ability to mix parallel/sequential for more complex flows. At a minimum a two level hierarchy (tasks/steps for example). but as per previous comment we can omit for now.

**Comment by psschwei** [comment]
I commented in Aki's PR, but one thing that jumps out to me in the schema is that this hardcodes the steps:

```yaml
  steps:
  - step1
  - step2
  - step3
  - step4
  step1:
    agent: agent1
  step2:
    agent: agent2
  step3:
    agent: agent1
  step4:
    agent: agent3
```

Could we define a `step` (singular) schema and then make `steps` (plural) a lists of `step`s ?
