### ISSUE TITLE
Define tool YAML and create the json schema for it

### ISSUE THREAD

**Issue by akihikokuroda** [i-am-bee/beeai-labs#275]
Define the tool yaml

We can probably use the [tool definition of the MCP](https://spec.modelcontextprotocol.io/specification/2024-11-05/server/tools/#tool ) as a model for this. 

Here are some MCP tools: https://github.com/modelcontextprotocol/servers/tree/main/src

**Comment by akihikokuroda** [comment]
Here is an example of the yaml.  we need to define the list of inputschema and outputschema types.  WDYT?  @maximilien @psschwei @george-lhj 
```yaml
apiVersion: maestro/v1alpha1
kind: Tool
metadata:
  name: e-mail
  labels:
    app: e-mail
spec:
  description: "Send an e-mail"
  inputSchema:
    type: jsonSchema
    schema: |
       {
          "title": "E-mail Tool",
          "description": "Create and send an e-mail",
          "type": "object",
          "properties": {
            "parameters": {
              "to": {
                "type": "array,
                "description": "list of e-mail addresses"
                "items": {
                  "type": string,
                  "description": "e-mail address"
                }  
              }
              "subject": {
                "type": "string",
               "description": "e-mail subject"  
              }
              "body": {
                "type": "string",
                "description": "e-mail message"  
              }
            }
          }
       }   
  outputSchema:
    type: text
    schema:
```

**Comment by psschwei** [comment]
Yeah, the industry seems to be standardizing on MCP, so being compatible with it is very important

**Comment by akihikokuroda** [comment]
In addition to the local definition of the schemas, we add the reference to the schema.  
```yaml
apiVersion: maestro/v1alpha1
kind: Tool
metadata:
  name: e-mail
  labels:
    app: e-mail
spec:
  description: "Send an e-mail"
  inputSchema:
    type: reference
    url: http://xxx.yyy.zzz/e-mail
  outputSchema:
    type: text
    schema:
```
