### ISSUE TITLE
feature: add events to workflow: external and scheduled events

### ISSUE THREAD

**Issue by maximilien** [i-am-bee/beeai-labs#289]
Often workflow steps need to be executed on a schedule or due to an event. Therefore there is a need to define a way for a workflow step to execute based on a scheduled (e.g., a [cron](https://www.ibm.com/docs/en/db2-as-a-service?topic=task-unix-cron-format) definition) or due to an external event (e.g., [CloudEvent](https://cloudevents.io/)).

- [x] proposal schema change
- [x] add `cron` example and test
- [ ]  add `CloudEvent` example and test

CC: @akihikokuroda

**Comment by maximilien** [comment]
Here is a proposal for `cron`:

```yaml
apiVersion: maestro/v1
kind: Workflow
metadata:
  name: simple cron workflow
  labels:
    app: cron-example    
spec:
  template:
    metadata:
      name: cron-example
      labels:
        app: cron
        use-case: test
    agents:
        - test1
        - test2
    prompt: This is a test input
    exception: step2
    steps:
      - name: step1
         agent: test2
         on:
           cron: "10 14 * * 1"
      - name: step2
        agent: test2
```

The main change is this bit of YAML:

```yaml
         on:
           cron: "10 14 * * 1"
```
which specifies the `cron` job `"10 14 * * 1"` which will call `step1` every week at 2:10PM.

We could also move the cron bit outside of the step definition but wanted to keep it clean since would allow each step to define their cron jobs.

WDYT @akihikokuroda and @psschwei ?

**Comment by akihikokuroda** [comment]
It may be better to have the corn at the workflow level (probably specified in the template level) to make it simple.

**Comment by maximilien** [comment]
But then we cannot use it for many steps unless we allow it to be used specify many steps. So something like:

```yaml
apiVersion: maestro/v1
kind: Workflow
metadata:
  name: simple cron workflow
  labels:
    app: cron-example    
spec:
  template:
    metadata:
      name: cron-example
      labels:
        app: cron
        use-case: test
     on:
       cron: "10 14 * * 1"
       step: step1
       steps:
         - step2
         - step3
    agents:
        - test1
        - test2
        - test3
    prompt: This is a test input
    exception: step2
    steps:
      - name: step1
         agent: test2
      - name: step2
        agent: test2
      - name: step3
        agent: test3
```

**Comment by maximilien** [comment]
After discussing with @akihikokuroda we agreed on two possibilities:

```yaml
    on:
       cron: "10 14 * * 1"
       step: step1
       exit: { input.exit == True }
```
OR calling multiple steps in sequence:

```yaml
    on:
       cron: "10 14 * * 1"
       steps: 
         - step2
         - step3
       exit: { input.count == 3 }
```
And the agreement is to also execute the workflow once before the the cron job.
