### ISSUE TITLE
Complete Workflow::to_mermaid markdown with other workflow elements

### ISSUE THREAD

**Issue by maximilien** [i-am-bee/beeai-labs#297]
PR #296 solved issue #290 but needs to be enhance to include markdown representation for:

- [x] add CI to run `maestro mermaid <workflow.yaml>` on all workflow YAMLs
- [x] workflow `condition` (case/do/default and if/then/else)
- [x] workflow `exception` 
- [x] workflow `on` events sequence diagram 
- [x] workflow `parallel` sequence diagram 
- [x] workflow `loop` sequence diagram 

- [x] workflow `exception` flowchart
- [x] workflow `on` events flowchart
- [x] workflow `parallel` flowchart
- [x] workflow `loop` flowchart

CC: @akihikokuroda

**Comment by psschwei** [comment]
Once we can represent all workflows as mermaid markdown, I think it would be worth asking the question of can we go the other way? Submit a workflow to maestro as mermaid markdown and have it parse it into the correct order...

**Comment by psschwei** [comment]
https://github.com/i-am-bee/beeai-labs/issues/303

**Comment by maximilien** [comment]
```yaml
apiVersion: maestro/v1
kind: Workflow
metadata:
  name: maestro-deployment
  labels:
    app: example2
spec:
  template:
    metadata:
      name: maestro-deployment
      labels:
        app: example
        use-case: test
    agents:
      - agent1
      - agent2
      - agent3
    prompt: This is a prompt
    start: step1
    exception: step3
    steps:
      - name: step1
        agent: agent1
        condition:
          - if: (in.some_condition == True)
            then: step2
            else: step3
      - name: step2
        agent: agent2
      - name: step3
        agent: agent3
        condition:
          - case: (in.some_condition == True)
            do: step2
          - case: (in.some_condition == False)
            do: step3
          - default: step3
```

generates this piece of mermaid sequenceDiagram

```mermaid
sequenceDiagram
participant agent1
participant agent2
participant agent3
agent1->>agent2: step1
agent2->>agent3: step2
agent3->>agent3: step3
```

and this piece of mermaid flowchart

```mermaid
flowchart LR
agent1-- step1 -->agent2
agent2-- step2 -->agent3
agent3-- step3 -->agent3
```
