### ISSUE TITLE
Generate workflow from mermaid representation

### ISSUE THREAD

**Issue by psschwei** [i-am-bee/beeai-labs#303]
As I user, I want to be able to draft my workflow as a mermaid diagram and have maestro generate a workflow for me.

For example, I want to be able to input:

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

and get this as output:

```yaml
apiVersion: maestro/v1
kind: Workflow
metadata:
  name: parallel
spec:
  template:
    metadata:
      name: parallel
    agents:
        - A
        - B
        - C
        - D
    prompt: something
    steps:
      - name: start
        agent: A
      - name: parallel
        parallel:
        - B
        - C
      - name: result
        agent: D
```
