### ISSUE TITLE
bug: meta agents workflow workflow does not show mermaid diagram

### ISSUE THREAD

**Issue by maximilien** [i-am-bee/beeai-labs#386]
This was a subtask in PR #365

**Comment by george-lhj** [comment]
```yaml

apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: meta_agent_workflow
  labels:
    project: maestro-demo
spec:
  template:
    metadata:
      name: meta_agent_workflow
      labels:
        project: maestro-demo
    agents:
      - NLP Agent Planner V2
      - Format Workflow Agent V2
      - Workflow V2
    prompt: I want to compare the current weather with the historical averages. To do this, I probably will need 2 agents, one to retrieve the weather and one to compare to the historical average.
    steps:
      - name: English Instructions to Prompt
        agent: NLP Agent Planner V2
      - name: Specify Agents for Workflow Generation
        agent: Format Workflow Agent V2
      - name: Creating Workflow YAML file
        agent: Workflow V2
```


This is the workflow file in meta agents that isn't being displayed properly
@maximilien
