### ISSUE TITLE
feature: long running steps

### ISSUE THREAD

**Issue by maximilien** [i-am-bee/beeai-labs#514]
In some workflows a step might take a "huge" amount of time to complete. This could be minutes, hours, or days. We need a way to deal with this. One proposal is to have async steps and allow for callbacks. For instance:

```yaml
    steps:
      - name: long-running
        agent: slow-agent
        type: async
        callback: long-running-callback
            webhook: http://localhost:8000/long-running-callback
```

WDYT @akihikokuroda? We could probably dynamically create the callback for such steps. 

We might also need to have a way to specify that a step is waiting on a callback. Like a `trigger` definition. 

Anyhow, LMK what you think of above and let's try it. I can then create a "trigger" issue to address.

CC: @AngeloDanducci @psschwei for long running jobs need.

**Comment by psschwei** [comment]
[async component](https://github.com/knative-extensions/async-component/) rides again! 😄

**Comment by akihikokuroda** [comment]
It's another option.  In that case, the first workflow waits until the job completion and sends a slack message.

**Comment by akihikokuroda** [comment]
Behavior for this:
```
    steps:
      - name: long-running
        agent: slow-agent
        type: async
        callback: long-running-callback
            webhook: http://localhost:8000/long-running-callback
```

1. start a new server or add the new entry to the existing server that waits for the call back
2. start the `slow-agent`
3. if type is `async`, move to the next step, otherwise wait for the `slow-agent` response

Is this correct?

There are some other questions.
- s `async` valid without `callback`?
- Is there any option for `callback` other than `webhook`?

For the `trigger`, there is `event` that only supports `cron` job now.  Is it reasonable to extend the `event` to handle this call back?

Thanks!

**Comment by maximilien** [comment]
OK, here’s a more detailed design that @akihikokuroda and I came up with:

```yaml

  triggers:
   - name: test_callback
      kind: callback
        callback: /test_callback
   - name: test_slack
       kind: slack
          channel: test_channel
          message: done
   - name: test_email
        kind: email
          address: maxim@us.ibm.com
step:
  …
  name: long_running
  async: true
    on_start: test_email
    on_finish: test_callback
step:
  …
step:
  …
step:
  …
  name: test_wait
  trigger: test_callback
```
